application: touchtypepractice
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /external
  static_dir: external
- url: /html
  static_dir: html  
- url: /js
  static_dir: js
- url: /.*
  script: app.application
  
libraries:
- name: webapp2
  version: latest